vim.api.nvim_set_keymap("n", "<ESC>,", "<c-w>5<", {noremap = true})
vim.api.nvim_set_keymap("n", "<ESC>.", "<c-w>5>", {noremap = true})
vim.api.nvim_set_keymap("n", "<ESC>/", "<c-w>-", {noremap = true})
vim.api.nvim_set_keymap("n", "<ESC>;", "<c-w>+", {noremap = true})
=======
vim.keymap.set("n", "<A-,>", "<c-w>5<", { desc = "Resize split left" })
vim.keymap.set("n", "<A-.>", "<c-w>5>", { desc = "Resize split right" })
vim.keymap.set("n", "<A-/>", "<c-w>-", { desc = "Resize split down" })
vim.keymap.set("n", "<A-;>", "<c-w>+", { desc = "Resize split up" })
>>>>>>> eb947f0 (Add configs)
