-- local wk = require("which-key")
vim.g.copilot_enabled = false
--
-- -- Toggle function for Copilot
-- local function toggle_copilot()
--     vim.g.copilot_enabled = not vim.g.copilot_enabled
--     if vim.g.copilot_enabled then
--         print("Copilot enabled")
--     else
--         print("Copilot disabled")
--     end
-- end
--
-- -- Registering with which-key
-- wk.add({
--     { "<M-x>", "copilot#Accept()", desc = "Copilot Accept", mode = "i", expr = true, silent = true },
--     { "<M-w>", "copilot#AcceptWord()", desc = "Copilot Accept Word", mode = "i", expr = true, silent = true },
--     { "<M-W>", "copilot#AcceptLine()", desc = "Copilot Accept Line", mode = "i", expr = true, silent = true },
-- })
--
-- wk.add({
--     { "<leader>cp", toggle_copilot, desc = "Toggle Copilot", icon = { icon = "󰚩", color = "red" } },
-- })
