export ANKI_WAYLAND=${ANKI_WAYLAND:-1}
# export DISPLAY=${DISPLAY:-:0} # TODO: Test
export HYPRCURSOR_SIZE=${HYPRCURSOR_SIZE:-24}
export HYPRLAND_CMD=${HYPRLAND_CMD:-"hyprland"}

export WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-"wayland-1"}
export WLR_NO_HARDWARE_CURSORS=${WLR_NO_HARDWARE_CURSORS:-1}
export XCURSOR_SIZE=${XCURSOR_SIZE:-24}
export XDG_BACKEND=${XDG_BACKEND:-"wayland"}
export XDG_CURRENT_DESKTOP=${XDG_CURRENT_DESKTOP:-"Hyprland"}
